order_sections <- data.frame(
  order_sections = c(1, 2, 3, 4),
  section = c("general_information", "study_information", "methodology", "results")
)

questions_sections <- list(
  "id_response" = c(
    "Timestamp" = "Timestamp",
    "doi" = "doi",
    "Initials of the reviewer filling the form" = "reviwer_initial",
    "itc_number" = "itc_number"
  ),
  "general_information" = c(
    "Medical Condition of Interest Name" = "condition_name",
    "Countries of first author affiliations" = "country_first_author",
    "Countries of last author affiliations" = "country_last_author",
    "Positions of study investigators (for any authors of the article, any that applies)" = "positions",
    "At least one author affiliated with a department of Biostatistics, Epidemiology, Public Health, Pharmacoepidemiology, or a Clinical Research unit, or private data analysis company" = "methodologist_yn",
    "Mentioned sources of funding" = "funding_source",
    "Ties with pharmaceutical industry mentionned in competing interest/conflict of interest/disclaimer, or any equivalent section in the article" = "pharmaceutical_ties_yn",
    "Mention of a systematic review to find the studies to compare treatments of interest" = "systematic_review_yn"
  ),
  "study_information" = c(
    "study_number" = "study_number",
    "Patient-level data used" = "ipd_yn",
    "Clinical Trial" = "ct_yn",
    "NCT (only for clinical trial registered on clinicaltrials.gov)" = "nct",
    "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu" = "eudract",
    "Data source name (only if observational study or clinical trial without NCT)" = "data_source_name",
    "Country where the clinical trial/observational study was conducted (international if more than one)" = "country_study",
    "Phase of the clinical trial (clinical trial only)" = "ct_phase",
    "Number of treatment arms (clinical trial only)" = "ct_arms"
  ),
  "methodology" = c(
    "Treatment name 1" = "treatment_name_ipd",
    "Study 'number(s)' for treatment 1" = "studies_number_ipd",
    "Treatment name 2" = "treatment_name_nonipd",
    "Study 'number(s)' for treatment 2" = "stduies_number_nonipd",
    "Type of population-adjusted indirect comparisons performed" = "paic_type",
    "Anchored comparison?" = "anchored_yn",
    "Form of the indirect comparison" = "paic_form",
    "Definition of a single primary outcome for the indirect comparison" = "primary_outcome_yn",
    "Primary Outcome Name (first one mentioned in the text of the results part if no primary outcome defined)" = "outcome_name",
    "Primary outcome: variable type" = "outcome_variable_type",
    "Justification for selecting variables to be included in the adjustment model (in the main text)" = "variables_selection_justification",
    "Inclusion of prognostic factors in the adjustment/matching model" = "prognostic_factors_yn",
    "Inclusion of treatment-effect modifiers in the adjustment/matching model" = "tem_yn",
    "Mention of the MAIC weights estimation model / STC adjustment model details in the main text **or supplemental materials** (ie matching on first moment, second moment, including interaction term, etc)" = "adjustment_model_details_yn",
    "Discussion of the choice of the scale for the outcome in the main text (ie natural outcome scale vs transformed outcome scale)" = "scale_choice_yn"
  ),
  "results" = c(
    "Sample size of the population of interest in the non IPD treatment arm" = "ss_ttt_nonipd",
    "If anchored comparison, sample size of the population of interest in the non IPD treatment anchor arm" = "ss_anchor_nonipd",
    "Initial sample size of the population of interest in the IPD treatment arm" = "ss_ttt_ipd",
    "Sample size in the IPD treatment arm used in the indirect comparison, ie effective sample size after reweighting for MAIC; or sample size used in the regression model for STC" = "ss_adjusted_ttt_ipd",
    "If anchored comparison, initial sample size of the population of interest in the IPD anchor arm" = "ss_anchor_ipd",
    "If anchored comparison, effective sample size after reweighting for MAIC; or sample size used in the regression model for STC in the IPD anchor arm" = "ss_adjusted_anchor_ipd",
    "If anchored, total initial sample size IPD" = "ss_total_ipd",
    "If anchored, total ESS IPD" = "ss_total_adjusted_ipd",
    "If anchored, total sample size non IPD" = "ss_total_nonipd",
    "Reporting of a weights' distribution evaluation (MAIC)" = "weights_yn",
    "Reporting of the list of the covariates adjusted for/matched on" = "covariates_yn",
    "Number of covariates adjusted for/matched on" = "covariates_n",
    "geographical region" = "adjustment_geographical",
    "Covariates adjusted for/matched on in the indirect comparison" = "covariates_names",
    "Primary outcome: treatment effect contrast" = "contrast_effect_type",
    "Direction of the treatment effect contrast: IPD treatment is:" = "contrast_effect_direction",
    "Primary outcome: unadjusted treatment effect" = "contrast_effect_unadjusted_value",
    "p-value for the unadjusted treatment effect (or 95 CI if pvalue is not provided, written as [X.XX-Y.YY])" = "contrast_effect_unadjusted_pvalci",
    "Primary outcome: adjusted treatment effect" = "contrast_effect_adjusted_value",
    "p-value for the adjusted treatment effect (or 95 CI if pvalue is not provided, written as [X.XX" = "contrast_effect_adjusted_pvalci"
  ),
  "Notes" = c("notes")
)


list_questions <- c(
  "Edit URL" = "url",
  "Timestamp" = "timestamp",
  "itc_number" = "n_itc",
  "doi" = "doi",
  "Initials of the reviewer filling the form" = "reviewer",
  "Medical Condition of Interest Name" = "Medical Condition of Interest Name",
  "Countries of first author affiliations" = "Countries of first author affiliations",
  "Countries of last author affiliations" = "Countries of last author affiliations",
  "Positions of study investigators (for any authors of the article, any that applies)" = "Positions of study investigators (for any authors of the article, any that applies)",
  "At least one author affiliated with a department of Biostatistics, Epidemiology, Public Health, Pharmacoepidemiology, or a Clinical Research unit, or private data analysis company" = "At least one author affiliated with a department of Biostatistics, Epidemiology, Public Health, Pharmacoepidemiology, or a Clinical Research unit, or private data analysis company",
  "Mentioned sources of funding" = "Mentioned sources of funding",
  "Ties with pharmaceutical industry mentionned in competing interest/conflict of interest/disclaimer, or any equivalent section in the article" = "Ties with pharmaceutical industry mentionned in competing interest/conflict of interest/disclaimer, or any equivalent section in the article",
  "Mention of a systematic review to find the studies to compare treatments of interest" = "Mention of a systematic review to find the studies to compare treatments of interest",
  "study_number" = "study_number_1",
  "Patient-level data used" = "Patient-level data used_1",
  "Clinical Trial" = "Clinical Trial_1",
  "NCT (only for clinical trial registered on clinicaltrials.gov)" = "NCT (only for clinical trial registered on clinicaltrials.gov)_1",
  "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu" = "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu_1",
  "Data source name (only if observational study or clinical trial without NCT)" = "Data source name (only if observational study or clinical trial without NCT)_1",
  "Country where the clinical trial/observational study was conducted (international if more than one)" = "Country where the clinical trial/observational study was conducted (international if more than one)_1",
  "Phase of the clinical trial (clinical trial only)" = "Phase of the clinical trial (clinical trial only)_1",
  "Number of treatment arms (clinical trial only)" = "Number of treatment arms (clinical trial only)_1",
  "study_number" = "study_number_2",
  "Patient-level data used" = "Patient-level data used_2",
  "Clinical Trial" = "Clinical Trial_2",
  "NCT (only for clinical trial registered on clinicaltrials.gov)" = "NCT (only for clinical trial registered on clinicaltrials.gov)_2",
  "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu" = "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu_2",
  "Data source name (only if observational study or clinical trial without NCT)" = "Data source name (only if observational study or clinical trial without NCT)_2",
  "Country where the clinical trial/observational study was conducted (international if more than one)" = "Country where the clinical trial/observational study was conducted (international if more than one)_2",
  "Phase of the clinical trial (clinical trial only)" = "Phase of the clinical trial (clinical trial only)_2",
  "Number of treatment arms (clinical trial only)" = "Number of treatment arms (clinical trial only)_2",
  "study_number" = "study_number_3",
  "Patient-level data used" = "Patient-level data used_3",
  "Clinical Trial" = "Clinical Trial_3",
  "NCT (only for clinical trial registered on clinicaltrials.gov)" = "NCT (only for clinical trial registered on clinicaltrials.gov)_3",
  "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu" = "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu_3",
  "Data source name (only if observational study or clinical trial without NCT)" = "Data source name (only if observational study or clinical trial without NCT)_3",
  "Country where the clinical trial/observational study was conducted (international if more than one)" = "Country where the clinical trial/observational study was conducted (international if more than one)_3",
  "Phase of the clinical trial (clinical trial only)" = "Phase of the clinical trial (clinical trial only)_3",
  "Number of treatment arms (clinical trial only)" = "Number of treatment arms (clinical trial only)_3",
  "study_number" = "study_number_4",
  "Patient-level data used" = "Patient-level data used_4",
  "Clinical Trial" = "Clinical Trial_4",
  "NCT (only for clinical trial registered on clinicaltrials.gov)" = "NCT (only for clinical trial registered on clinicaltrials.gov)_4",
  "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu" = "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu_4",
  "Data source name (only if observational study or clinical trial without NCT)" = "Data source name (only if observational study or clinical trial without NCT)_4",
  "Country where the clinical trial/observational study was conducted (international if more than one)" = "Country where the clinical trial/observational study was conducted (international if more than one)_4",
  "Phase of the clinical trial (clinical trial only)" = "Phase of the clinical trial (clinical trial only)_4",
  "Number of treatment arms (clinical trial only)" = "Number of treatment arms (clinical trial only)_4",
  "study_number" = "study_number_5",
  "Patient-level data used" = "Patient-level data used_5",
  "Clinical Trial" = "Clinical Trial_5",
  "NCT (only for clinical trial registered on clinicaltrials.gov)" = "NCT (only for clinical trial registered on clinicaltrials.gov)_5",
  "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu" = "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu_5",
  "Data source name (only if observational study or clinical trial without NCT)" = "Data source name (only if observational study or clinical trial without NCT)_5",
  "Country where the clinical trial/observational study was conducted (international if more than one)" = "Country where the clinical trial/observational study was conducted (international if more than one)_5",
  "Phase of the clinical trial (clinical trial only)" = "Phase of the clinical trial (clinical trial only)_5",
  "Number of treatment arms (clinical trial only)" = "Number of treatment arms (clinical trial only)_5",
  "Treatment name 1" = "Treatment name 1",
  "Study 'number(s)' for treatment 1" = "Study 'number(s)' for treatment 1",
  "Treatment name 2" = "Treatment name 2",
  "Study 'number(s)' for treatment 2" = "Study 'number(s)' for treatment 2",
  "Type of population-adjusted indirect comparisons performed" = "Type of population-adjusted indirect comparisons performed",
  "Anchored comparison?" = "Anchored comparison?",
  "Form of the indirect comparison" = "Form of the indirect comparison",
  "Definition of a single primary outcome for the indirect comparison" = "Definition of a single primary outcome for the indirect comparison",
  "Primary Outcome Name (first one mentioned in the text of the results part if no primary outcome defined)" = "Primary Outcome Name (first one mentioned in the text of the results part if no primary outcome defined)",
  "Primary outcome: variable type" = "Primary outcome: variable type",
  "Justification for selecting variables to be included in the adjustment model (in the main text)" = "Justification for selecting variables to be included in the adjustment model (in the main text)",
  "Inclusion of prognostic factors in the adjustment/matching model" = "Inclusion of prognostic factors in the adjustment/matching model",
  "Inclusion of treatment-effect modifiers in the adjustment/matching model" = "Inclusion of treatment-effect modifiers in the adjustment/matching model",
  "Mention of the MAIC weights estimation model / STC adjustment model details in the main text **or supplemental materials** (ie matching on first moment, second moment, including interaction term, etc)" = "Mention of the MAIC weights estimation model / STC adjustment model details in the main text **or supplemental materials** (ie matching on first moment, second moment, including interaction term, etc)",
  "Discussion of the choice of the scale for the outcome in the main text (ie natural outcome scale vs transformed outcome scale)" = "Discussion of the choice of the scale for the outcome in the main text (ie natural outcome scale vs transformed outcome scale)",
  "Sample size of the population of interest in the non IPD treatment arm" = "Sample size of the population of interest in the non IPD treatment arm",
  "If anchored comparison, sample size of the population of interest in the non IPD treatment anchor arm" = "If anchored comparison, sample size of the population of interest in the non IPD treatment anchor arm",
  "Initial sample size of the population of interest in the IPD treatment arm" = "Initial sample size of the population of interest in the IPD treatment arm",
  "Sample size in the IPD treatment arm used in the indirect comparison, ie effective sample size after reweighting for MAIC; or sample size used in the regression model for STC" = "Sample size in the IPD treatment arm used in the indirect comparison, ie effective sample size after reweighting for MAIC; or sample size used in the regression model for STC",
  "If anchored comparison, initial sample size of the population of interest in the IPD anchor arm" = "If anchored comparison, initial sample size of the population of interest in the IPD anchor arm",
  "If anchored comparison, effective sample size after reweighting for MAIC; or sample size used in the regression model for STC in the IPD anchor arm" = "If anchored comparison, effective sample size after reweighting for MAIC; or sample size used in the regression model for STC in the IPD anchor arm",
  "Reporting of a weights' distribution evaluation (MAIC)" = "Reporting of a weights' distribution evaluation (MAIC)",
  "Reporting of the list of the covariates adjusted for/matched on" = "Reporting of the list of the covariates adjusted for/matched on",
  "Number of covariates adjusted for/matched on" = "Number of covariates adjusted for/matched on",
  "Covariates adjusted for/matched on in the indirect comparison" = "Covariates adjusted for/matched on in the indirect comparison",
  "Primary outcome: treatment effect contrast" = "Primary outcome: treatment effect contrast",
  "Direction of the treatment effect contrast: IPD treatment is:" = "Direction of the treatment effect contrast: IPD treatment is:",
  "Primary outcome: unadjusted treatment effect" = "unadjusted_ttt_effect",
  "p-value for the unadjusted treatment effect (or 95 CI if pvalue is not provided, written as [X.XX-Y.YY])" = "unadjusted_pvalue_CI",
  "Primary outcome: adjusted treatment effect" = "adjusted_ttt_effect",
  "p-value for the adjusted treatment effect (or 95 CI if pvalue is not provided, written as [X.XX;Y.YY])" = "adjusted_pvalue_CI",
  "Notes" = "Notes",
  "geographical region" = "geographical region",
  "If anchored, total initial sample size IPD" = "If anchored, total initial sample size IPD",
  "If anchored, total ESS IPD" = "If anchored, total ESS IPD",
  "If anchored, total sample size non IPD" = "If anchored, total sample size non IPD"
)


columns_to_review <- c(
  "NCT (only for clinical trial registered on clinicaltrials.gov)",
  "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu",
  "Data source name (only if observational study or clinical trial without NCT)",
  "Mention of a systematic review to find the studies to compare treatments of interest",
  "Treatment name 1",
  "Study 'number(s)' for treatment 1",
  "Treatment name 2",
  "Study 'number(s)' for treatment 2",
  "Type of population-adjusted indirect comparisons performed",
  "Anchored comparison?",
  "Form of the indirect comparison",
  "Definition of a single primary outcome for the indirect comparison",
  "Primary Outcome Name (first one mentioned in the text of the results part if no primary outcome defined)",
  "Primary outcome: variable type",
  "Justification for selecting variables to be included in the adjustment model (in the main text)",
  "Inclusion of prognostic factors in the adjustment/matching model",
  "Inclusion of treatment-effect modifiers in the adjustment/matching model",
  "Mention of the MAIC weights estimation model / STC adjustment model details in the main text **or supplemental materials** (ie matching on first moment, second moment, including interaction term, etc)",
  "Discussion of the choice of the scale for the outcome in the main text (ie natural outcome scale vs transformed outcome scale)",
  "Sample size of the population of interest in the non IPD treatment arm",
  "If anchored comparison, sample size of the population of interest in the non IPD treatment anchor arm",
  "Initial sample size of the population of interest in the IPD treatment arm",
  "Sample size in the IPD treatment arm used in the indirect comparison, ie effective sample size after reweighting for MAIC; or sample size used in the regression model for STC",
  "If anchored comparison, initial sample size of the population of interest in the IPD anchor arm",
  "If anchored comparison, effective sample size after reweighting for MAIC; or sample size used in the regression model for STC in the IPD anchor arm",
  "Reporting of a weights' distribution evaluation (MAIC)",
  "Reporting of the list of the covariates adjusted for/matched on",
  "Number of covariates adjusted for/matched on",
  "Covariates adjusted for/matched on in the indirect comparison",
  "Primary outcome: treatment effect contrast",
  "Direction of the treatment effect contrast: IPD treatment is:",
  "unadjusted_ttt_effect",
  "unadjusted_pvalue_CI",
  "adjusted_ttt_effect",
  "adjusted_pvalue_CI"
)

extra_columns <- c(
  "geographical region" = "geographical region",
  "If anchored, total initial sample size IPD" = "If anchored, total initial sample size IPD",
  "If anchored, total ESS IPD" = "If anchored, total ESS IPD",
  "If anchored, total sample size non IPD" = "If anchored, total sample size non IPD"
)



# question types ----------------------------------------------------------

qcm_questions <- c(
  "Positions of study investigators (for any authors of the article, any that applies)",
  "Mentioned sources of funding",
  "Phase of the clinical trial (clinical trial only)",
  "Justification for selecting variables to be included in the adjustment model (in the main text)",
  "Covariates adjusted for/matched on in the indirect comparison"
)

qcu_questions <- c(
  "At least one author affiliated with a department of Biostatistics, Epidemiology, Public Health, Pharmacoepidemiology, or a Clinical Research unit, or private data analysis company",
  "Ties with pharmaceutical industry mentionned in competing interest/conflict of interest/disclaimer, or any equivalent section in the article",
  "Mention of a systematic review to find the studies to compare treatments of interest" = "Mention of a systematic review to find the studies to compare treatments of interest",
  "Patient-level data used",
  "Clinical Trial",
  "Number of treatment arms (clinical trial only)",
  "Type of population-adjusted indirect comparisons performed",
  "Anchored comparison?",
  "Form of the indirect comparison",
  "Definition of a single primary outcome for the indirect comparison",
  "Primary outcome: variable type",
  "Primary outcome: treatment effect contrast",
  "Inclusion of prognostic factors in the adjustment/matching model",
  "Inclusion of treatment-effect modifiers in the adjustment/matching model",
  "Mention of the MAIC weights estimation model / STC adjustment model details in the main text **or supplemental materials** (ie matching on first moment, second moment, including interaction term, etc)",
  "Discussion of the choice of the scale for the outcome in the main text (ie natural outcome scale vs transformed outcome scale)",
  "Reporting of a weights' distribution evaluation (MAIC)",
  "Reporting of the list of the covariates adjusted for/matched on",
  "geographical region",
  "Direction of the treatment effect contrast: IPD treatment is:"
)

numerical_questions <- c(
  "study_number",
  "Sample size of the population of interest in the non IPD treatment arm",
  "Initial sample size of the population of interest in the IPD treatment arm",
  "Sample size in the IPD treatment arm used in the indirect comparison, ie effective sample size after reweighting for MAIC; or sample size used in the regression model for STC",
  "Number of covariates adjusted for/matched on",
  "Primary outcome: unadjusted treatment effect",
  "If anchored, total initial sample size IPD",
  "If anchored, total ESS IPD",
  "If anchored, total sample size non IPD",
  "If anchored comparison, sample size of the population of interest in the non IPD treatment anchor arm",
  "If anchored comparison, initial sample size of the population of interest in the IPD anchor arm",
  "If anchored comparison, effective sample size after reweighting for MAIC; or sample size used in the regression model for STC in the IPD anchor arm"
)


characters_questions <- c(
  "Medical Condition of Interest Name",
  "Countries of first author affiliations",
  "Countries of last author affiliations",
  "NCT (only for clinical trial registered on clinicaltrials.gov)",
  "EudraCT (only for clinical trials registered on clinicaltrialsregister.eu",
  "Country where the clinical trial/observational study was conducted (international if more than one)",
  "Data source name (only if observational study or clinical trial without NCT)",
  "Treatment name 1",
  "Treatment name 2",
  "Study 'number(s)' for treatment 1",
  "Study 'number(s)' for treatment 2",
  "Primary Outcome Name (first one mentioned in the text of the results part if no primary outcome defined)",
  "p-value for the unadjusted treatment effect (or 95 CI if pvalue is not provided, written as [X.XX-Y.YY])",
  "p-value for the adjusted treatment effect (or 95 CI if pvalue is not provided, written as [X.XX;Y.YY])"
)
